### ISSUE TITLE
The accuracy on ImageNet dataset

### ISSUE THREAD

**Issue by rose-jinyang** [dipuk0506/SpinalNet#1]
Hello
How are you?
Thanks for contributing to this paper and project.
We want to know the accuracy of this method on ImageNet.
Thanks.

**Comment by dipuk0506** [comment]
Hi, 
I am fine.
We haven't tested our proposed SpinalNet on the ImageNet dataset due to hardware limitations. Moreover, ImageNet dataset is not public anymore. We are facing difficulties in downloading data.

We may investigate our SpinalNet on ImageNet in the future.

Regards-
Dipu Kabir

**Comment by lucyfan7266** [comment]
Nice work. Is it accepted?
