### ISSUE TITLE
Universal approximation proof verified in experiements?

### ISSUE THREAD

**Issue by flyingdorothia** [dipuk0506/SpinalNet#2]
Hi,

This architecture is constructed in nn.sequential layers. But I wonder, as shown in your fig.3 of the paper, did you do the actual test to show the two structure are equivalent?

**Comment by dipuk0506** [comment]
Hi Fan,
We have verified the Figure for common types of activation functions. 'Universal Approximation' section of the supplementary material of the paper presents our [investigation.](https://github.com/dipuk0506/SpinalNet/blob/master/Supplementary%20Materials%20SpinalNet.pdf)
