### ISSUE TITLE
Assigning Half_width and layer_width

### ISSUE THREAD

**Issue by sayannath** [dipuk0506/SpinalNet#4]
Hi!!

Can you just tell me how you assigned `Half_width` and `layer_width` [here](https://github.com/dipuk0506/SpinalNet/blob/master/CIFAR-10/CNN_dropout_SpinalFC_CIFAR10.py#L25-L26).

Thanks

**Comment by dipuk0506** [comment]
Hi Sayannath, 
Half_width is the half of the input width after flattening.

layer_width is the width of each sub layer in SpinalNet fully-connected layer.
