### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by eirene8** [dipuk0506/SpinalNet#5]
Hello, 
a question concerning the normalization you are using: How did you choose the mean and std in the script for transfer learning on STL-10 and why is it the same for other datasets and not an individual, specific one for each of them? Are these values calculated on CIFAR (mean=[0.507, 0.487, 0.441], std=[0.267, 0.256, 0.276] )? And is there a reason you are using different values for showing the image (mean = [0.485, 0.456, 0.406]),  std = [0.229, 0.224, 0.225]; the ones usually used for Imagenet)? 
Thank you very much!

**Comment by dipuk0506** [comment]
Thank you for your question.

I tried several values of normalizations and selected a value providing good results. Showing images is not related to optimization. I  collected the 'imshow' function from somewhere on the internet and used it as it was.

Recently, I checked that, the code runs well even we delete augmentations inside 'imshow' function. Again, thank you for reading all details.

**Comment by eirene8** [comment]
I see. Thank you very much for this very quick answer! 

Ah, I guess in the originally use case the imshow function was used to show images from Imagenet that were standardized before (with the respective values). But as the differences in the standardization values (those for Imagenet and those that you are using) are pretty small, the slightly different back-transformation probably does not really show :)

**Comment by dipuk0506** [comment]
Hi, I have fixed the issue. The new notebook of STL-10 shows the result of the same transformation. Again, thank you.
