### ISSUE TITLE
EMNIST balanced ACC

### ISSUE THREAD

**Issue by Bellman281** [dipuk0506/SpinalNet#6]
Dear Scholars.

I have trained the SpinalNet model on EMNIST BALANCED data. Unfortunately I could achieved 85.82 ACC after 100 epoch training. Would you please comment if there is a way to get better accuracy on this dataset? I have prepared the notebook as following for convenience:

https://github.com/Bellman281/Character_Recognition_Models

Any comments is highly appreciated.

**Comment by dipuk0506** [comment]
Hi Bellman,
Please use one script from the MNIST VGG folder.
EMNIST digits or EMNIST letters. They are the high-performing ones.
https://github.com/dipuk0506/SpinalNet/tree/master/MNIST_VGG

Also, you can practice transfer learning and get good performance in fewer epochs. For MNIST transfer learning, see the notebook: https://github.com/dipuk0506/SpinalNet/blob/master/Jupyter%20Notebooks/transfer-learning-on-fashion-mnist-dataset.ipynb
